require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe JavascriptsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Javascript. As you add validations to Javascript, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JavascriptsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all javascripts as @javascripts" do
      javascript = Javascript.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:javascripts)).to eq([javascript])
    end
  end

  describe "GET show" do
    it "assigns the requested javascript as @javascript" do
      javascript = Javascript.create! valid_attributes
      get :show, {:id => javascript.to_param}, valid_session
      expect(assigns(:javascript)).to eq(javascript)
    end
  end

  describe "GET new" do
    it "assigns a new javascript as @javascript" do
      get :new, {}, valid_session
      expect(assigns(:javascript)).to be_a_new(Javascript)
    end
  end

  describe "GET edit" do
    it "assigns the requested javascript as @javascript" do
      javascript = Javascript.create! valid_attributes
      get :edit, {:id => javascript.to_param}, valid_session
      expect(assigns(:javascript)).to eq(javascript)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Javascript" do
        expect {
          post :create, {:javascript => valid_attributes}, valid_session
        }.to change(Javascript, :count).by(1)
      end

      it "assigns a newly created javascript as @javascript" do
        post :create, {:javascript => valid_attributes}, valid_session
        expect(assigns(:javascript)).to be_a(Javascript)
        expect(assigns(:javascript)).to be_persisted
      end

      it "redirects to the created javascript" do
        post :create, {:javascript => valid_attributes}, valid_session
        expect(response).to redirect_to(Javascript.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved javascript as @javascript" do
        post :create, {:javascript => invalid_attributes}, valid_session
        expect(assigns(:javascript)).to be_a_new(Javascript)
      end

      it "re-renders the 'new' template" do
        post :create, {:javascript => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested javascript" do
        javascript = Javascript.create! valid_attributes
        put :update, {:id => javascript.to_param, :javascript => new_attributes}, valid_session
        javascript.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested javascript as @javascript" do
        javascript = Javascript.create! valid_attributes
        put :update, {:id => javascript.to_param, :javascript => valid_attributes}, valid_session
        expect(assigns(:javascript)).to eq(javascript)
      end

      it "redirects to the javascript" do
        javascript = Javascript.create! valid_attributes
        put :update, {:id => javascript.to_param, :javascript => valid_attributes}, valid_session
        expect(response).to redirect_to(javascript)
      end
    end

    describe "with invalid params" do
      it "assigns the javascript as @javascript" do
        javascript = Javascript.create! valid_attributes
        put :update, {:id => javascript.to_param, :javascript => invalid_attributes}, valid_session
        expect(assigns(:javascript)).to eq(javascript)
      end

      it "re-renders the 'edit' template" do
        javascript = Javascript.create! valid_attributes
        put :update, {:id => javascript.to_param, :javascript => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested javascript" do
      javascript = Javascript.create! valid_attributes
      expect {
        delete :destroy, {:id => javascript.to_param}, valid_session
      }.to change(Javascript, :count).by(-1)
    end

    it "redirects to the javascripts list" do
      javascript = Javascript.create! valid_attributes
      delete :destroy, {:id => javascript.to_param}, valid_session
      expect(response).to redirect_to(javascripts_url)
    end
  end

end
